[package]
name = "rocky28447/roact-rodux"
version = "0.3.4"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
React = "jsdotlua/react@17.0.2"
ReactRoblox = "jsdotlua/react-roblox@17.0.2"
Rodux = "roblox/rodux@4.0.0-rc.0"
