[package]
name = "rocky28447/roact-rodux"
version = "0.3.3"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
React = "core-packages/react@17.0.1-rc.18"
ReactRoblox = "core-packages/react-roblox@17.0.1-rc.16"
Rodux = "roblox/rodux@4.0.0-rc.0"
