[package]
name = "rocky28447/roact-rodux"
version = "0.3.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Roact = "jsdotlua/react@17.0.1"
Rodux = "roblox/rodux@4.0.0-rc.0"
